# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

def spider(query):
    profile = webdriver.FirefoxProfile()
    profile.set_preference("permissions.default.image", 2)
    options = Options()
    options.add_argument('-headless')

    driver = webdriver.Firefox(firefox_profile=profile, options=options)

    driver.get("https://fitgirl-repacks.site/?s="+query)
    driver.set_window_size(890, 753)
    #time.sleep(5)
    results=driver.find_elements_by_xpath("//h1[@class='entry-title']/a")
    for result in results:
        print(result.get_attribute('href'))

    #driver.find_element(By.XPATH, "/html/body/div/div/section/div/article[1]/header/h1/a")
    driver.find_element(By.CSS_SELECTOR, ".entry-title > a").click()
    magnet=driver.find_element(By.CSS_SELECTOR, ".entry-content > ul:nth-child(5) > li:nth-child(1) > a:nth-child(3)").get_attribute("href")
    print(magnet)

print("Enter name of the game")
query=input()
spider(query)
  
