# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

def spider(query):
    rlinks=[]
    profile = webdriver.FirefoxProfile()
    profile.set_preference("permissions.default.image", 2)
    options = Options()
    options.add_argument('-headless')

    driver = webdriver.Firefox(firefox_profile=profile, options=options)

    driver.get("https://fitgirl-repacks.site/?s="+query)
    driver.set_window_size(890, 753)
    results=driver.find_elements_by_xpath("//h1[@class='entry-title']/a")
    print('\nSelect one of these:')
    i=1
    for result in results:
        print(str(i)+". "+result.text)
        rlinks.append(result.get_attribute('href'))
        i=i+1
    driver.close()
    print("\nEnter your choice :")
    choice=int(input())
    clink=rlinks[choice-1]
    print("\n"+clink)
    return clink


